### PR TITLE
Add Example App

### PR DESCRIPTION
**Pull request by thecoolwinter**
### Description

Adds an example app.

### Related Issues

* N/A

### Checklist

- [x] I read and understood the [contributing guide](https://github.com/CodeEditApp/CodeEdit/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/CodeEditApp/CodeEdit/blob/main/CODE_OF_CONDUCT.md)
- [x] The issues this PR addresses are related to each other
- [x] My changes generate no new warnings
- [x] My code builds and runs on my machine
- [x] My changes are all related to the related issue above
- [x] I documented my code

### Screenshots

https://github.com/CodeEditApp/CodeEditSourceEditor/assets/35942988/f11e5cc1-c159-45dd-bdb7-55d389804a3e

### CODE REVIEW

**Review by EstebanBorai — APPROVED** [review]

**Comment by EstebanBorai** [comment]
As I understand this will help us try out on development, right?

**Comment by thecoolwinter** [comment]
Yes it will! I think I need to update the testing script tho, so I'll take a look at that tomorrow

**Comment by EstebanBorai** [comment]
> Yes it will! I think I need to update the testing script tho, so I'll take a look at that tomorrow

Great! Do you think CodeEditTextView can have a similar update?

**Comment by 0xWDG** [comment]
Looks good, but the tests seems to fail :(

**Pull request closed without merging**
